import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/layout/header";
import Footer from "@/app/layout/footer";

const inter = Inter({
    variable: '--font-inter',
    subsets: ["latin"],
    weight: ["400", "600", "700"],
    style: ["normal"]
})

export const metadata: Metadata = {
  title: "OTU Blueprint",
  description: "Generated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <Header />
                    <article className="min-h-screen overflow-x-hidden">
                        {children}
                    </article>
                <Footer />
            </body>
        </html>
    );
}
